// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb2wXIzsBu59TSYB68FPFtqmnpbO7gQwA',
    appId: '1:536667372041:web:625b1af574f54c84ab56d8',
    messagingSenderId: '536667372041',
    projectId: 'doanphimhuit',
    authDomain: 'doanphimhuit.firebaseapp.com',
    storageBucket: 'doanphimhuit.firebasestorage.app',
    measurementId: 'G-ERZ716RXDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPGRlQNppt5GUg8iPo69Z9VRjwzY3CcNc',
    appId: '1:536667372041:android:012a26e1192aab26ab56d8',
    messagingSenderId: '536667372041',
    projectId: 'doanphimhuit',
    storageBucket: 'doanphimhuit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcHxyuMFKADS_C8u4VmYQ2mGOaopF827w',
    appId: '1:536667372041:ios:47d2a453f3dcbb05ab56d8',
    messagingSenderId: '536667372041',
    projectId: 'doanphimhuit',
    storageBucket: 'doanphimhuit.firebasestorage.app',
    androidClientId: '536667372041-4def0b7nmfi2elh7is9k8klsj2fff88l.apps.googleusercontent.com',
    iosClientId: '536667372041-ec4jb9hko61gaqtmsdqav9ofncmmvu4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhom4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcHxyuMFKADS_C8u4VmYQ2mGOaopF827w',
    appId: '1:536667372041:ios:47d2a453f3dcbb05ab56d8',
    messagingSenderId: '536667372041',
    projectId: 'doanphimhuit',
    storageBucket: 'doanphimhuit.firebasestorage.app',
    androidClientId: '536667372041-4def0b7nmfi2elh7is9k8klsj2fff88l.apps.googleusercontent.com',
    iosClientId: '536667372041-ec4jb9hko61gaqtmsdqav9ofncmmvu4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhom4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb2wXIzsBu59TSYB68FPFtqmnpbO7gQwA',
    appId: '1:536667372041:web:deabcecae246c20fab56d8',
    messagingSenderId: '536667372041',
    projectId: 'doanphimhuit',
    authDomain: 'doanphimhuit.firebaseapp.com',
    storageBucket: 'doanphimhuit.firebasestorage.app',
    measurementId: 'G-7RSXYGVHNN',
  );
}
